Name: Oktamer
IconPath: oktamer.jpg
SoundPath: dekat.wav
Description: |
    No rage de nos ravages
BrainsPackage: teams.oktamer
ScriptImplementation: python
AgentsBrainClasses:
    WarBase: WarBase.py
    WarExplorer: WarExplorer.py
    WarLight: WarLight.py
    WarHeavy: WarHeavy.py
    WarRocketLauncher: WarRocketLauncher.py
    WarKamikaze: WarKamikaze.py
    WarEngineer: WarEngineer.py
    WarTurret: WarTurret.py
